name: Test Azure Login

on:
  workflow_dispatch:   # só roda manualmente

jobs:
  test-login:
    runs-on: ubuntu-latest
    environment: dev   # se os secrets estão no environment "dev"
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Verify subscription
        run: |
          az account show
